server:
  port: 8060
spring:
  application:
    name: rocketme-producer
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 47.111.136.90:9876
        bindings:
          output1:
            producer:
              group: test-group-1
      bindings:
        output1: {destination: test-topic-1}
eureka:
  client:
    serviceUrl:
      ####注册中心地址(单节点)
      defaultZone: http://127.0.0.1:8010/eureka/
      #      defaultZone: http://${eureka.instance.host}:${eureka.server.port}/eureka/
      ####注册中心地址(集群，填写其他节点地址，这里需要注意的是，即时写了集群注册中心的多个地址，默认只会在第一个地址对应的注册中心的web页面看到这个服务，
      ####因为集群注册中心共享同一份服务列表，但是同时只有一个注册中心监控该服务，所以使用单点注册配置即可)
      #defaultZone: http://${eureka.instance.hostname}:8762/eureka/
    ####将自己注册到注册中心 ,默认为true，所以eureka client端可以不设置此参数
    registerWithEureka: true
    ####获取eureka注册中心上的服务列表，默认为true（同上面的属性一起一起使用）
    fetchRegistry: true