server:
  port: 9000
spring:
  profiles: dev
  application:
    name: configServer
  cloud:
    config:
      label: master #仓库分支
      server:
        svn:
          uri: http://svn.com #svn地址
          username: #svn用户名
          password: #svn密码